### PR TITLE
Rexbranch

### PR DESCRIPTION
**Pull request by RuixuanDSBA**
Merge rexmeng's databrike files

### CODE REVIEW

**Comment by RuixuanDSBA** [comment]
code created and checked by REX [RexDmeng](https://github.com/RexDmeng)

**Review by RuixuanDSBA — COMMENTED** [review]
How to view it on jupyter notebook?

**Review by RuixuanDSBA — COMMENTED** [review]
Do we upload all databirkes files?

**Comment by RexDmeng** [comment]
merge

**Comment by RexDmeng** [comment]
yes, please merge all of them

**Review by RexDmeng — COMMENTED** [review]
all down

**Review by RexDmeng — APPROVED** [review]
all finished

**Comment by RuixuanDSBA** [comment]
Thanks Rex,  the original branch can be deleted

**Pull request merged**
